/*CH-230-A
A7p3.c
Kamila Ziza
kziza@constructor.university
*/



# we use the Makefile from lecture 7
CC = gcc
CFLAGS = -Wall

# we create the object files
OBJ = linked_list.o use_linked_list.o

# the executable
all: use_linked_list

# we run the executable
use_linked_list: $(OBJ)
				 $(CC) $(CFLAGS) -o use_linked_list $(OBJ)

#the inside of the object file
use_linked_list.o: linked_list.h use_linked_list.c

# the inside of the 
linked_list.o: linked_list.h linked_list.c

# we delete the object files
clean:
	   rm -f use_linked_list *.o
       rm -f linked_list *.o